import "./globals.css" 
import RootProvider from "./RootProvider";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><RootProvider>{children}</RootProvider></body>
    </html>
  )
}
